"""

Revision ID: 483f6fffc80e
Revises: 2785e49daf72
Create Date: 2024-06-12 10:26:23.989404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '483f6fffc80e'
down_revision: Union[str, None] = '2785e49daf72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fleetship', sa.Column('mac_address', sa.String(), nullable=True))
    op.drop_column('sensor', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('fleetship', 'mac_address')
    # ### end Alembic commands ###
